=== AmritSingh1502/Web-Technology-CTA/queries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="queries">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="query" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="description" type="xs:string" />
                            <xs:element name="author" type="xs:string" />
                            <xs:element name="date" type="xs:string" />
                            <xs:element name="tags">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tag" maxOccurs="unbounded"
                                            type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="answers">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="answer" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="description" type="xs:string" />
                                                    <xs:element name="author" type="xs:string" />
                                                    <xs:element name="date" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AmritSingh1502/Web-Technology-CTA/queries.xml
<queries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="queries.xsd">
    <query>
        <description> Question or Problem goes here </description>
        <author>Person who posted the query</author>
        <date> Posted On </date>
        <tags>
            <tag>Related Keyword</tag>
            <tag>Related Keyword</tag>
            <tag>Related Keyword</tag>
            <tag>Related Keyword</tag>
        </tags>
        <answers>
            <answer>
                <description>Solution Submitted</description>
                <author>Posted by</author>
                <date>Posted on </date>
            </answer>
            <answer>
                <description>Solution Submitted</description>
                <author>Posted by</author>
                <date>posted on </date>
            </answer>
        </answers>
    </query>
    <query>
        <description> Question or Problem goes here </description>
        <author>Person who posted the query</author>
        <date> Posted On </date>
        <tags>
            <tag>Related Keyword</tag>
            <tag>Related Keyword</tag>
            <tag>Related Keyword</tag>
            <tag>Related Keyword</tag>
        </tags>
        <answers>
            <answer>
                <description>SOluton Submitted</description>
                <author>POsted by</author>
                <date>posted on </date>
            </answer>
            <answer>
                <description>SOluton Submitted</description>
                <author>POsted by</author>
                <date>posted on </date>
            </answer>
        </answers>
    </query>
</queries>
